-- MySQL Script generated by MySQL Workbench
-- dom 27 oct 2019 15:45:15 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema asistencia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema asistencia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asistencia` DEFAULT CHARACTER SET utf8 ;
USE `asistencia` ;

-- -----------------------------------------------------
-- Table `asistencia`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(60) NOT NULL,
  `apellido_usuario` VARCHAR(60) NOT NULL,
  `carnet` VARCHAR(15) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `id_tipo_usuario` INT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_tipo_usuario_idx` (`id_tipo_usuario` ASC),
  CONSTRAINT `fk_tipo_usuario`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `asistencia`.`tipo_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`hora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`hora` (
  `id_hora` INT NOT NULL AUTO_INCREMENT,
  `hora` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_hora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`dia` (
  `id_dia` INT NOT NULL AUTO_INCREMENT,
  `dia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_dia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`horario` (
  `id_horario` INT NOT NULL AUTO_INCREMENT,
  `activo` TINYINT(1) NOT NULL,
  `id_hora` INT NOT NULL,
  `id_dia` INT NOT NULL,
  `id_materia` INT NOT NULL,
  PRIMARY KEY (`id_horario`),
  INDEX `fk_id_hora_idx` (`id_hora` ASC),
  INDEX `fk_id_dia_idx` (`id_dia` ASC),
  CONSTRAINT `fk_id_hora`
    FOREIGN KEY (`id_hora`)
    REFERENCES `asistencia`.`hora` (`id_hora`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_dia`
    FOREIGN KEY (`id_dia`)
    REFERENCES `asistencia`.`dia` (`id_dia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`materia` (
  `id_materia` INT NOT NULL AUTO_INCREMENT,
  `nombre_materia` VARCHAR(45) NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  `id_carrera` INT NOT NULL,
  PRIMARY KEY (`id_materia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`usuario_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`usuario_materia` (
  `id_usuario_materia` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_materia` INT NOT NULL,
  PRIMARY KEY (`id_usuario_materia`),
  INDEX `fk_id_usuario_idx` (`id_usuario` ASC),
  INDEX `fk_id_materia_idx` (`id_materia` ASC),
  CONSTRAINT `fk_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `asistencia`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_materia`
    FOREIGN KEY (`id_materia`)
    REFERENCES `asistencia`.`materia` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`asistencia` (
  `id_asistencia` INT NOT NULL AUTO_INCREMENT,
  `qr` INT NOT NULL,
  `validacion` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `id_usuario_materia` INT NOT NULL,
  PRIMARY KEY (`id_asistencia`),
  INDEX `fk_id_usuario_materia_idx` (`id_usuario_materia` ASC),
  CONSTRAINT `fk_id_usuario_materia`
    FOREIGN KEY (`id_usuario_materia`)
    REFERENCES `asistencia`.`usuario_materia` (`id_usuario_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`tipo_insignia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`tipo_insignia` (
  `id_tipo_insignia` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo_insignia` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_tipo_insignia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`insignia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`insignia` (
  `id_insignia` INT NOT NULL AUTO_INCREMENT,
  `nombre_insignia` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  `id_tipo_insignia` INT NOT NULL,
  PRIMARY KEY (`id_insignia`),
  INDEX `fk_id_tipo_insignia_idx` (`id_tipo_insignia` ASC),
  CONSTRAINT `fk_id_tipo_insignia`
    FOREIGN KEY (`id_tipo_insignia`)
    REFERENCES `asistencia`.`tipo_insignia` (`id_tipo_insignia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`usuario_insignia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`usuario_insignia` (
  `id_usuario_insignia` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_insignia` INT NOT NULL,
  PRIMARY KEY (`id_usuario_insignia`),
  INDEX `fk_id_usuario_idx` (`id_usuario` ASC),
  INDEX `fk_id_insignia_idx` (`id_insignia` ASC),
  CONSTRAINT `fk_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `asistencia`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_insignia`
    FOREIGN KEY (`id_insignia`)
    REFERENCES `asistencia`.`insignia` (`id_insignia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`horario_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`horario_materia` (
  `id_horario_materia` INT NOT NULL AUTO_INCREMENT,
  `id_horario` INT NOT NULL,
  `id_materia` INT NOT NULL,
  PRIMARY KEY (`id_horario_materia`),
  INDEX `fk_id_horario_idx` (`id_horario` ASC),
  INDEX `fk_id_materia_idx` (`id_materia` ASC),
  CONSTRAINT `fk_id_horario`
    FOREIGN KEY (`id_horario`)
    REFERENCES `asistencia`.`horario` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_materia`
    FOREIGN KEY (`id_materia`)
    REFERENCES `asistencia`.`materia` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`institucion` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`tipo_institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`tipo_institucion` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`institucion_caracteristica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`institucion_caracteristica` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`caracteristica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`caracteristica` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
